version: '3'

services:

  poligonos:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: poligonos
    ports:
      - 8080:8080
      - 5005:5005
    networks:
      - fk-network

volumes:
  fk-volume:

networks:
  fk-network:
    driver: bridge
